

### 1. 异常

#### 1.1 异常概念

* **异常** ：指的是程序在执行过程中，出现的非正常的情况，最终会导致JVM的非正常停止。

在Java等面向对象的编程语言中，异常本身是一个类，产生异常就是创建异常对象并抛出了一个异常对象。Java处理异常的方式是中断处理。

> 异常指的并不是语法错误,语法错了,编译不通过,不会产生字节码文件,根本不能运行.

#### 1.2 异常体系

异常机制其实是帮助我们**找到**程序中的问题，异常的根类是`java.lang.Throwable`，其下有两个子类：`java.lang.Error`与`java.lang.Exception`，平常所说的异常指`java.lang.Exception`。

![异常体系](images/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB.png)

**Throwable体系：**

* **Error**:严重错误Error，无法通过处理的错误，只能事先避免，好比绝症。
* **Exception**:表示异常，异常产生后程序员可以通过代码的方式纠正，使程序继续运行，是必须要处理的。好比感冒、阑尾炎。

#### 1.3 异常分类

`java.lang.Throwable`：类是 Java 语言中所有错误或异常的超类

​	**Exception**：编译器异常，进行编译（写代码）Java程序出现的问题

​		RuntimeException：运行期异常，Java程序运行过程中出现的问题

#### 1.4 异常的产生过程解析

![异常产生过程分析](D:\les sylvia de documents\study-notes\Java\img\异常产生过程分析.jpg)

### 2. 异常处理

Java异常处理的五个关键字：try、catch、finally、throw、throws

#### 2.1 throw抛出异常

1. 作用：可以使用throw关键字在指定的方法中抛出指定的异常

2. 使用格式：`throw new xxxException("异常产生的原因");`

   例如：

   ```Java
   throw new NullPointerException("要访问的arr数组不存在");
   
   throw new ArrayIndexOutOfBoundsException("该索引在数组中不存在，已超出范围");
   ```

   ```Java
   public class ThrowDemo {
       public static void main(String[] args) {
           //创建一个数组 
           int[] arr = {2,4,52,2};
           //根据索引找对应的元素 
           int index = 4;
           int element = getElement(arr, index);
   
           System.out.println(element);
           System.out.println("over");
       }
       /*
        * 根据 索引找到数组中对应的元素
        */
       public static int getElement(int[] arr,int index){ 
          	//判断  索引是否越界
           if(index<0 || index>arr.length-1){
                /*
                判断条件如果满足，当执行完throw抛出异常对象后，方法已经无法继续运算。
                这时就会结束当前方法的执行，并将异常告知给调用者。这时就需要通过异常来解决。 
                 */
                throw new ArrayIndexOutOfBoundsException("哥们，角标越界了~~~");
           }
           int element = arr[index];
           return element;
       }
   }
   ```

   

3. 注意：

   - throw关键字必须写在方法的内部

   - throw关键字后边new的对象必须是Exception或者Exception的子类对象

   - throw关键字抛出指定的异常对象，我们就必须处理这个异常对象

     throw关键字后边创建的是RuntimeException或者是RuntimeException的子类对象，我们可以不处理，默认交给JVM处理（打印异常对象，中断程序）

     throw关键字后边创建的是编译异常（写代码的时候报错），我们就必须处理这个异常，要么throws，要么try ... catch

#### 2.2 Objects非空判断

还记得我们学习过一个类Objects吗，曾经提到过它由一些静态的实用方法组成，这些方法是null-save（空指针安全的）或null-tolerant（容忍空指针的），那么在它的源码中，对对象为null的值进行了抛出异常操作。

* `public static <T> T requireNonNull(T obj)`:查看指定引用对象不是null。

查看源码发现这里对为null的进行了抛出异常操作：

```Java
public static <T> T requireNonNull(T obj) {
    if (obj == null)
      	throw new NullPointerException();
    return obj;
}
```

```Java
public class Demo04Objects {
    public static void main(String[] args) {
        method(null);
    }

    private static void method(Object obj) {
//        if(obj == null) {
//            throw new NullPointerException("传递对象的值是null");
//        }
        Objects.requireNonNull(obj,"传递对象的值是null");
    }
}
```

#### 2.3 throws声明异常

throws关键字：异常处理的第一种方式：交给别人处理

作用：

- 当方法内部抛出异常对象的时候，那么我们就必须处理这个异常对象
- 可以使用throws关键字处理异常对象，会把异常对象声明抛出给方法的调用者处理（自己不处理，交给别人处理），最终交给JVM处理 ---->  中断处理

使用格式：在方法声明时使用

```java 
修饰符 返回值类型 方法名(参数列表) throws AAAException,BBBException...{
	throw new AAAException("产生原因");
	throw new BBBception("产生原因");
	...
}
```

注意：

- throws关键字必须写在方法声明处

- throws关键字后边生命的异常必须是Exception或者是Exception的子类

- 方法内部如果抛出了多个异常对象，那么throws后边必须也声明多个异常

  ​	如果抛出的多个异常对象有子父类关系，那么直接声明父类异常即可

- 调用了一个声明抛出异常的方法，我们就必须处理声明的异常

  ​	要么继续使用throws声明抛出，交给方法的调用者处理，最终交给JVM

  ​	要么try...catch自己处理异常

#### 2.4 捕获异常try ... catch

try ... catch：异常处理的第二种方式：自己处理异常

格式：

```Java
//catch可以有多个
try{
	可能产生异常的代码
}catch(定义一个异常的变量，用来接收try中抛出的异常对象){
	异常的处理逻辑，产生异常对象之后，怎么处理异常对象
	一般在工作中，会把异常的信息记录到一个日志中
}
...
catch(异常类名 变量名){
    
}
```

注意：

- try中可能会抛出多个异常对象,那么就可以使用多个catch来处理这些异常对象

- 如果try中产生了异常,那么就会执行catch中的异常处理逻辑,执行完毕catch中的处理逻辑,继续执行try...catch之后的代码

   如果try中没有产生异常,那么就不会执行catch中异常的处理逻辑,执行完try中的代码,继续执行try...catch之后的代码

```Java
public class Demo05TryCatch {
    public static void main(String[] args) {
        try{
            readFile("d:\\a.tx");
        }catch (IOException e) {
            System.out.println("catch --->  文件的后缀名不对");
        }
        System.out.println("后续代码");
    }

    private static void readFile(String fileName) throws IOException {
        if(!fileName.endsWith(".txt")) {
            throw new IOException("文件的后缀名不对");
        }
        System.out.println("路径没有问题，读取文件");
    }
}
```

#### 2.5 Throwable类中3个异常处理的方法

Throwable类中定义了一些查看方法:

* `public String getMessage()`:获取异常的描述信息,原因（简短描述）


* `public String toString()`:获取异常的类型和异常描述信息（详细信息字符串）。
* `public void printStackTrace()`:JVM打印异常对象，默认此方法，打印的异常信息最全面

   *包含了异常的类型,异常的原因,还包括异常出现的位置,在开发和调试阶段,都得使用printStackTrace。*

```Java
try{
    readFile("d:\\a.tx");
}catch (IOException e) {
    System.out.println(e.getMessage());  //文件的后缀名不对
    System.out.println(e.toString());  //java.io.IOException: 文件的后缀名不对
    System.out.println(e);  //java.io.IOException: 文件的后缀名不对
    e.printStackTrace();
    /*
            * java.io.IOException: 文件的后缀名不对
	                at day05.ExceptionAndThread.Demo05TryCatch.readFile(Demo05TryCatch.java:20)
	                at day05.ExceptionAndThread.Demo05TryCatch.main(Demo05TryCatch.java:8)
	        */
}
```

#### 2.6 finally代码块

**finally**：有一些特定的代码无论异常是否发生，都需要执行。另外，因为异常会引发程序跳转，导致有些语句执行不到。而finally就是解决这个问题的，在finally代码块中存放的代码都是一定会被执行的。

什么时候的代码必须最终执行？

当我们在try语句块中打开了一些物理资源(磁盘文件/网络连接/数据库连接等),我们都得在使用完之后,最终关闭打开的资源。

finally的语法:

 try...catch....finally:自身需要处理异常,最终还得关闭资源。

> 注意:finally不能单独使用。

比如在我们之后学习的IO流中，当打开了一个关联文件的资源，最后程序不管结果如何，都需要把这个资源关闭掉。

```Java
try{
    readFile("d:\\a.tx");
}catch (IOException e) {
    e.printStackTrace();
}finally {
    System.out.println("资源释放");
}
```

#### 2.7 异常注意事项

多个异常使用捕获又该如何处理呢？

1. 多个异常分别处理。
2. 多个异常一次捕获，多次处理。
3. 多个异常一次捕获一次处理。

一般我们是使用一次捕获多次处理方式，格式如下：

```Java
try{
     编写可能会出现异常的代码
}catch(异常类型A  e){  当try中出现A类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}catch(异常类型B  e){  当try中出现B类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}
```

> 注意:这种异常处理方式，要求多个catch中的异常不能相同；
>
> ​          若catch中的多个异常之间有子父类异常的关系，那么子类异常要求在上面的catch处理，父类异常在下面的catch处理。

* **运行时异常被抛出可以不处理。即不捕获也不声明抛出。**

* 如果finally有return语句,永远返回finally中的结果,避免该情况. 

* 如果父类抛出了多个异常,子类重写父类方法时,抛出和父类相同的异常或者是父类异常的子类或者不抛出异常。

* 父类方法没有抛出异常，子类重写父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出

> 子类继承父类，只能抛出范围小于等于父类异常的异常（子类或本身）